title: Spore Studio
iconURL: assets/logo-tran-pos.png
theme: jekyll-theme-leaf

# for a clean URL
permalink: :slug

social:
  linkedin: Jorge Rodr√≠guez Castillo
  github: sporestudio

plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
hyvor_talk_website_id: 14
google_analytics: UA-NNNNNNNN-N